language: java
jdk: oraclejdk8
sudo: false
script:
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
language: java
git:
  depth: 1
dist: trusty
cache:
  directories:
  - "$HOME/.m2"
addons:
  sonarcloud:
    organization: "arnclaudel-github"